# fly.toml app configuration file generated for meal-planner-zzlx on 2026-05-11T02:06:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'meal-planner-zzlx'
primary_region = 'iad'

[build]

[env]
  MEAL_PLANNER_DB = '/data/meal_planner.db'

[[mounts]]
  source = 'meal_planner_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
